In [1]:
import json
import pandas as pd

login = './logins.json'
d_ch = './ultimate_data_challenge.json'

with open(d_ch) as f:
    d_cha = json.load(f)

In [2]:
d_c = pd.DataFrame(d_cha)

In [3]:
d_c.head(2)

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,ultimate_black_user,weekday_pct
0,3.67,5.0,4.7,1.1,King's Landing,2014-06-17,iPhone,2014-01-25,15.4,4,True,46.2
1,8.26,5.0,5.0,1.0,Astapor,2014-05-05,Android,2014-01-29,0.0,0,False,50.0

In [8]:
d_c.describe()

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,surge_pct,trips_in_first_30_days,weekday_pct
count,50000.000000,49799.000000,41878.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,5.796827,4.778158,4.601559,1.074764,8.849536,2.278200,60.926084
std,5.707357,0.446652,0.617338,0.222336,19.958811,3.792684,37.081503
min,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,2.420000,4.700000,4.300000,1.000000,0.000000,0.000000,33.300000
50%,3.880000,5.000000,4.900000,1.000000,0.000000,1.000000,66.700000
75%,6.940000,5.000000,5.000000,1.050000,8.600000,3.000000,100.000000
max,160.960000,5.000000,5.000000,8.000000,100.000000,125.000000,100.000000

In [9]:
d_c.info()
d_c.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
avg_dist                  50000 non-null float64
avg_rating_by_driver      49799 non-null float64
avg_rating_of_driver      41878 non-null float64
avg_surge                 50000 non-null float64
city                      50000 non-null object
last_trip_date            50000 non-null object
phone                     49604 non-null object
signup_date               50000 non-null object
surge_pct                 50000 non-null float64
trips_in_first_30_days    50000 non-null int64
ultimate_black_user       50000 non-null bool
weekday_pct               50000 non-null float64
dtypes: bool(1), float64(6), int64(1), object(4)
memory usage: 4.2+ MB

Index(['avg_dist', 'avg_rating_by_driver', 'avg_rating_of_driver', 'avg_surge',
       'city', 'last_trip_date', 'phone', 'signup_date', 'surge_pct',
       'trips_in_first_30_days', 'ultimate_black_user', 'weekday_pct'],
      dtype='object')

In [10]:
d_c.sort_values('last_trip_date')

,avg_dist,avg_rating_by_driver,avg_rating_of_driver,avg_surge,city,last_trip_date,phone,signup_date,surge_pct,trips_in_first_30_days,ultimate_black_user,weekday_pct
31425,4.31,5.0,NaN,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
10729,19.67,5.0,3.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
40336,5.98,5.0,5.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
34828,2.45,5.0,5.0,1.25,Astapor,2014-01-01,iPhone,2014-01-01,100.0,1,False,100.0
37295,0.77,5.0,3.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
9941,1.61,5.0,NaN,2.00,Winterfell,2014-01-01,Android,2014-01-01,100.0,1,False,100.0
13542,3.08,5.0,NaN,1.50,Winterfell,2014-01-01,iPhone,2014-01-01,100.0,1,False,100.0
39857,9.97,5.0,5.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
19976,4.74,5.0,5.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
48271,8.05,5.0,NaN,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,True,100.0
11259,5.23,5.0,5.0,1.00,King's Landing,2014-01-01,Android,2014-01-01,0.0,1,False,100.0
3112,3.00,5.0,5.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
9242,0.97,5.0,5.0,1.00,Astapor,2014-01-01,Android,2014-01-01,0.0,1,False,100.0
33809,6.03,5.0,5.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
15256,4.86,5.0,4.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
6052,6.69,4.0,NaN,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
5080,6.17,4.0,4.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
5582,2.42,3.0,4.0,1.00,Winterfell,2014-01-01,Android,2014-01-01,0.0,1,False,100.0
6650,3.00,5.0,5.0,1.00,Astapor,2014-01-01,Android,2014-01-01,0.0,1,False,100.0
34898,3.02,5.0,5.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,2,False,100.0
37344,2.14,5.0,NaN,1.00,Winterfell,2014-01-01,Android,2014-01-01,0.0,1,False,100.0
39490,1.25,2.0,2.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
16039,4.45,5.0,2.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
20806,6.49,5.0,NaN,1.00,Winterfell,2014-01-01,Android,2014-01-01,0.0,1,True,100.0
33241,6.83,3.0,4.0,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
22924,13.84,5.0,4.0,1.00,King's Landing,2014-01-01,Android,2014-01-01,0.0,1,False,100.0
12840,2.74,5.0,5.0,1.00,Winterfell,2014-01-01,Android,2014-01-01,0.0,1,True,100.0
29219,7.67,4.0,NaN,1.00,Winterfell,2014-01-01,iPhone,2014-01-01,0.0,1,False,100.0
5276,3.77,5.0,5.0,1.00,Winterfell,2014-01-01,Android,2014-01-01,0.0,1,True,100.0
44807,2.69,5.0,NaN,1.00,King's Landing,2014-01-01,iPhone,2014-01-01,0.0,1,True,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
22453,3.15,4.9,4.0,1.00,Astapor,2014-07-01,iPhone,2014-01-23,0.0,2,True,100.0
3824,2.86,4.8,5.0,1.02,Winterfell,2014-07-01,iPhone,2014-01-06,8.3,1,False,58.3
4313,5.86,4.8,4.7,1.25,Winterfell,2014-07-01,iPhone,2014-01-11,11.1,0,False,100.0
23010,3.97,4.8,3.0,1.00,Winterfell,2014-07-01,iPhone,2014-01-22,0.0,2,False,92.3
38779,4.07,5.0,5.0,1.00,King's Landing,2014-07-01,iPhone,2014-01-26,0.0,0,False,100.0
48590,3.35,4.9,5.0,1.00,Winterfell,2014-07-01,iPhone,2014-01-04,0.0,0,False,41.7
32935,7.38,4.4,4.2,1.00,Astapor,2014-07-01,Android,2014-01-31,0.0,0,True,60.0
4212,1.53,4.7,4.3,1.00,King's Landing,2014-07-01,iPhone,2014-01-04,0.0,4,False,89.5
48601,2.97,4.6,4.7,1.08,Winterfell,2014-07-01,iPhone,2014-01-30,13.3,6,False,53.3
32962,4.91,4.3,5.0,1.00,Astapor,2014-07-01,iPhone,2014-01-10,0.0,1,False,66.7
14172,3.80,4.6,4.9,1.05,King's Landing,2014-07-01,iPhone,2014-01-17,6.3,4,False,71.9
32982,2.42,3.3,NaN,1.00,Winterfell,2014-07-01,iPhone,2014-01-23,0.0,0,False,100.0
33003,3.69,5.0,4.7,1.04,Winterfell,2014-07-01,iPhone,2014-01-12,8.3,3,False,33.3
33035,4.82,4.9,5.0,1.21,King's Landing,2014-07-01,iPhone,2014-01-30,30.9,19,False,54.6
14041,2.20,4.8,5.0,1.00,Winterfell,2014-07-01,Android,2014-01-15,0.0,0,False,50.0
4080,2.77,4.7,4.6,1.01,Winterfell,2014-07-01,iPhone,2014-01-10,2.2,6,False,66.7
4013,1.90,4.7,5.0,1.16,King's Landing,2014-07-01,iPhone,2014-01-25,24.6,1,True,68.9
4002,2.75,4.6,4.1,1.06,Winterfell,2014-07-01,iPhone,2014-01-04,7.4,13,True,63.0
22625,7.60,5.0,5.0,1.00,Winterfell,2014-07-01,iPhone,2014-01-28,0.0,1,False,100.0
42346,6.19,4.7,5.0,1.00,Winterfell,2014-07-01,iPhone,2014-01-28,0.0,5,False,75.0
45155,5.24,4.6,4.8,1.03,Winterfell,2014-07-01,iPhone,2014-01-28,5.7,3,False,66.0
45154,8.14,5.0,5.0,1.00,King's Landing,2014-07-01,Android,2014-01-19,0.0,1,True,60.0
45143,4.37,4.8,4.9,1.08,King's Landing,2014-07-01,iPhone,2014-01-29,7.7,4,False,76.9
38661,4.07,4.7,4.4,1.16,Winterfell,2014-07-01,iPhone,2014-01-18,28.1,4,False,65.6
14419,5.98,4.8,3.8,1.07,Astapor,2014-07-01,iPhone,2014-01-25,6.1,3,True,78.8
45126,6.13,4.6,4.6,1.02,Winterfell,2014-07-01,Android,2014-01-10,6.3,1,False,56.3
38651,10.19,5.0,4.9,1.00,King's Landing,2014-07-01,iPhone,2014-01-13,0.0,0,True,92.3
14473,5.06,5.0,5.0,1.00,King's Landing,2014-07-01,Android,2014-01-02,0.0,0,False,100.0
22735,8.71,5.0,5.0,1.00,Winterfell,2014-07-01,iPhone,2014-01-08,0.0,0,True,75.0
45357,3.90,4.9,4.4,1.02,Astapor,2014-07-01,iPhone,2014-01-28,1.4,5,False,76.4

In [11]:
from collections import Counter

Counter(d_c['last_trip_date'])

Counter({'2014-01-01': 128,
         '2014-01-02': 180,
         '2014-01-03': 128,
         '2014-01-04': 199,
         '2014-01-05': 270,
         '2014-01-06': 170,
         '2014-01-07': 186,
         '2014-01-08': 212,
         '2014-01-09': 194,
         '2014-01-10': 247,
         '2014-01-11': 440,
         '2014-01-12': 586,
         '2014-01-13': 207,
         '2014-01-14': 172,
         '2014-01-15': 242,
         '2014-01-16': 267,
         '2014-01-17': 335,
         '2014-01-18': 542,
         '2014-01-19': 848,
         '2014-01-20': 557,
         '2014-01-21': 335,
         '2014-01-22': 217,
         '2014-01-23': 270,
         '2014-01-24': 326,
         '2014-01-25': 601,
         '2014-01-26': 808,
         '2014-01-27': 291,
         '2014-01-28': 226,
         '2014-01-29': 274,
         '2014-01-30': 295,
         '2014-01-31': 394,
         '2014-02-01': 478,
         '2014-02-02': 330,
         '2014-02-03': 134,
         '2014-02-04': 87,
         '2014-02-05': 104,
         '2014-02-06': 119,
         '2014-02-07': 161,
         '2014-02-08': 210,
         '2014-02-09': 253,
         '2014-02-10': 104,
         '2014-02-11': 82,
         '2014-02-12': 104,
         '2014-02-13': 108,
         '2014-02-14': 138,
         '2014-02-15': 219,
         '2014-02-16': 271,
         '2014-02-17': 136,
         '2014-02-18': 99,
         '2014-02-19': 79,
         '2014-02-20': 74,
         '2014-02-21': 135,
         '2014-02-22': 161,
         '2014-02-23': 198,
         '2014-02-24': 82,
         '2014-02-25': 82,
         '2014-02-26': 79,
         '2014-02-27': 138,
         '2014-02-28': 143,
         '2014-03-01': 198,
         '2014-03-02': 280,
         '2014-03-03': 84,
         '2014-03-04': 69,
         '2014-03-05': 91,
         '2014-03-06': 118,
         '2014-03-07': 121,
         '2014-03-08': 160,
         '2014-03-09': 220,
         '2014-03-10': 69,
         '2014-03-11': 79,
         '2014-03-12': 86,
         '2014-03-13': 104,
         '2014-03-14': 126,
         '2014-03-15': 245,
         '2014-03-16': 354,
         '2014-03-17': 132,
         '2014-03-18': 124,
         '2014-03-19': 116,
         '2014-03-20': 113,
         '2014-03-21': 126,
         '2014-03-22': 191,
         '2014-03-23': 222,
         '2014-03-24': 103,
         '2014-03-25': 89,
         '2014-03-26': 115,
         '2014-03-27': 144,
         '2014-03-28': 152,
         '2014-03-29': 190,
         '2014-03-30': 243,
         '2014-03-31': 104,
         '2014-04-01': 84,
         '2014-04-02': 99,
         '2014-04-03': 109,
         '2014-04-04': 176,
         '2014-04-05': 213,
         '2014-04-06': 266,
         '2014-04-07': 124,
         '2014-04-08': 116,
         '2014-04-09': 103,
         '2014-04-10': 118,
         '2014-04-11': 126,
         '2014-04-12': 189,
         '2014-04-13': 291,
         '2014-04-14': 98,
         '2014-04-15': 83,
         '2014-04-16': 102,
         '2014-04-17': 129,
         '2014-04-18': 149,
         '2014-04-19': 184,
         '2014-04-20': 205,
         '2014-04-21': 144,
         '2014-04-22': 105,
         '2014-04-23': 118,
         '2014-04-24': 159,
         '2014-04-25': 172,
         '2014-04-26': 245,
         '2014-04-27': 304,
         '2014-04-28': 127,
         '2014-04-29': 118,
         '2014-04-30': 132,
         '2014-05-01': 167,
         '2014-05-02': 207,
         '2014-05-03': 257,
         '2014-05-04': 293,
         '2014-05-05': 129,
         '2014-05-06': 137,
         '2014-05-07': 142,
         '2014-05-08': 157,
         '2014-05-09': 210,
         '2014-05-10': 283,
         '2014-05-11': 317,
         '2014-05-12': 152,
         '2014-05-13': 129,
         '2014-05-14': 190,
         '2014-05-15': 201,
         '2014-05-16': 289,
         '2014-05-17': 384,
         '2014-05-18': 470,
         '2014-05-19': 253,
         '2014-05-20': 204,
         '2014-05-21': 208,
         '2014-05-22': 214,
         '2014-05-23': 263,
         '2014-05-24': 321,
         '2014-05-25': 397,
         '2014-05-26': 303,
         '2014-05-27': 165,
         '2014-05-28': 203,
         '2014-05-29': 222,
         '2014-05-30': 299,
         '2014-05-31': 419,
         '2014-06-01': 494,
         '2014-06-02': 208,
         '2014-06-03': 182,
         '2014-06-04': 240,
         '2014-06-05': 262,
         '2014-06-06': 314,
         '2014-06-07': 534,
         '2014-06-08': 527,
         '2014-06-09': 262,
         '2014-06-10': 244,
         '2014-06-11': 297,
         '2014-06-12': 351,
         '2014-06-13': 438,
         '2014-06-14': 665,
         '2014-06-15': 647,
         '2014-06-16': 310,
         '2014-06-17': 296,
         '2014-06-18': 400,
         '2014-06-19': 455,
         '2014-06-20': 612,
         '2014-06-21': 869,
         '2014-06-22': 1024,
         '2014-06-23': 546,
         '2014-06-24': 440,
         '2014-06-25': 603,
         '2014-06-26': 793,
         '2014-06-27': 1120,
         '2014-06-28': 1679,
         '2014-06-29': 2036,
         '2014-06-30': 1408,
         '2014-07-01': 548})

If a user is retained if they were 'active' in the preceding 30 days then given 7/1 as the current date, May and prior will be used as training data and after will be test data.